In [59]:
import numpy as np

In [60]:
working_time_matrix = np.mat([[1, 5, 5],
                              [1/5, 1, 1],
                              [1/5, 1, 1]])

salary_matrix = np.mat([[1, 5, 5],
                        [1/5, 1, 2],
                        [1/5, 1/2 ,1]])

safety_matrix = np.mat([[1, 3, 1],
                        [1/3, 1, 1/3],
                        [1, 3, 1]])

distance_matrix = np.mat([[1, 5, 7],
                          [1/5 ,1 ,3],
                          [1/7, 1/3, 1]])

manual_labour_matrix = np.mat([[1, 5, 5],
                               [1/5, 1, 1/2],
                               [1/5, 2, 1]])

In [80]:
# 工作时间 0
# 薪资 1
# 安全性 2
# 距离 3
# 劳动强度 4

prior_list = [0,4,3,2,1]
choice_matrix = np.zeros((5, 5))
choice_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
for i in range(len(prior_list)):
    for j in range(len(prior_list)):
        if j >= i:
            dist = (j - i) * 2 + 1
        else:
            dist = 1 / ((i - j) * 2 + 1)
        choice_matrix[prior_list[i], prior_list[j]] = dist

choice_matrix

array([[1.        , 9.        , 7.        , 5.        , 3.        ],
       [0.11111111, 1.        , 0.33333333, 0.2       , 0.14285714],
       [0.14285714, 3.        , 1.        , 0.33333333, 0.2       ],
       [0.2       , 5.        , 3.        , 1.        , 0.33333333],
       [0.33333333, 7.        , 5.        , 3.        , 1.        ]])

In [82]:
def get_weight(matrix):
    weight = np.real(np.array(np.linalg.eig(matrix)[1][:,0]).flatten())
    return weight / np.sum(weight)

In [83]:
working_time_weight = get_weight(working_time_matrix)
salary_weight = get_weight(salary_matrix)
safety_weight = get_weight(safety_matrix)
distance_weight = get_weight(distance_matrix)
manual_labour_weight = get_weight(manual_labour_matrix)

In [84]:
analysis_layer = [working_time_weight,
                  salary_weight,
                  safety_weight,
                  distance_weight,
                  manual_labour_weight]

In [85]:
choice_weight = get_weight(choice_matrix)
choice_weight

array([0.51281281, 0.03333518, 0.06337653, 0.12897642, 0.26149906])

In [58]:
weight = np.zeros(len(working_time_weight)).tolist()
for i in range(len(working_time_weight)):
    for j in range(len(choice_weight)):
        weight[i] += choice_weight[j] * analysis_layer[j][i]

weight


[0.7978250203806718, 0.14746952049413029, 0.054705459125197885]