In [11]:
import pandas as pd
import numpy as np
import sklearn.preprocessing

In [12]:
df = pd.read_csv('PersonDataSet.csv')
df

gender  height  weight  age category  from
0        M  168.64   69.47   19       本科  一线城市
1        M  170.08   54.23   19       本科  三线城市
2        F  158.15   65.07   22       专科  一线城市
3        F  164.14   83.73   18       专科  三线城市
4        M  170.06   82.34   18       专科  三线城市
..     ...     ...     ...  ...      ...   ...
995      M  162.53   73.11   21       专科  三线城市
996      M  159.26   69.90   19       本科  二线城市
997      F  158.92   79.84   18       专科  三线城市
998      M  169.45   75.35   19       本科  三线城市
999      F  167.36   75.71   18       专科  二线城市

[1000 rows x 6 columns]

In [13]:
gender_array = sklearn.preprocessing.LabelEncoder().fit_transform(np.array(df['gender']))
gender_array

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,

In [14]:
category_array = sklearn.preprocessing.LabelEncoder().fit_transform(np.array(df['category']))
category_array

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [15]:
from_array = sklearn.preprocessing.OneHotEncoder().fit_transform(np.array(df['from']).reshape(-1,1)).toarray()
from_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
print(gender_array.shape)
print(category_array.shape)
print(from_array.shape)

(1000,)
(1000,)
(1000, 3)


In [18]:
data = np.concatenate((gender_array.reshape(-1,1),
                       category_array.reshape(-1,1),
                       from_array,
                       np.array(df['height']).reshape(-1,1),
                       np.array(df['weight']).reshape(-1,1),
                       np.array(df['age']).reshape(-1,1),
                       ),axis=1)
data

array([[  1.  ,   1.  ,   1.  , ..., 168.64,  69.47,  19.  ],
       [  1.  ,   1.  ,   0.  , ..., 170.08,  54.23,  19.  ],
       [  0.  ,   0.  ,   1.  , ..., 158.15,  65.07,  22.  ],
       ...,
       [  0.  ,   0.  ,   0.  , ..., 158.92,  79.84,  18.  ],
       [  1.  ,   1.  ,   0.  , ..., 169.45,  75.35,  19.  ],
       [  0.  ,   0.  ,   0.  , ..., 167.36,  75.71,  18.  ]])

In [19]:
pd.DataFrame(data).to_csv('个人数据集-处理后.csv', header=['gender',
                                     'category',
                                     'from_1','from_2','from_3',
                                     'height','weight','age'])
